[package]
name = "lqos_bus"
version = "0.1.0"
edition = "2021"

[features]
default = ["equinix_tests"]
equinix_tests = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1"
anyhow = "1"
lqos_config = { path = "../lqos_config" }
tokio = { version = "1.22", features = [ "rt", "macros", "net", "io-util" ] }

[build-dependencies]
cc = "1.0"

[dev-dependencies]
criterion = { version = "0.3", features = [ "html_reports"] }

[[bench]]
name = "socket"
harness = false
