[package]
name = "lqos_bus"
version = "0.1.0"
edition = "2021"

[features]
default = ["equinix_tests"]
equinix_tests = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1"
thiserror = "1"
lqos_config = { path = "../lqos_config" }
lqos_utils = { path = "../lqos_utils" }
tokio = { version = "1", features = [ "rt", "macros", "net", "io-util", "time" ] }
log = "0"
nix = "0"

[build-dependencies]
cc = "1.0"

[dev-dependencies]
criterion = { version = "0", features = [ "html_reports", "async_tokio"] }

[[bench]]
name = "socket"
harness = false
