[package]
name = "lqosd"
version = "0.1.0"
edition = "2021"

[features]
default = ["equinix_tests"]
equinix_tests = []

[dependencies]
anyhow = "1"
lqos_config = { path = "../lqos_config" }
lqos_sys = { path = "../lqos_sys" }
lqos_queue_tracker = { path = "../lqos_queue_tracker" }
lqos_utils = { path = "../lqos_utils" }
tokio = { version = "1.22", features = [ "full", "parking_lot" ] }
lazy_static = "1.4"
parking_lot = "0.12"
lqos_bus = { path = "../lqos_bus" }
signal-hook = "0.3"
serde_json = "1"
serde = { version = "1.0", features = ["derive"] }
env_logger = "0"
log = "0"
nix = "0"
rayon = "1"
sysinfo = "0"

# Support JemAlloc on supported platforms
[target.'cfg(any(target_arch = "x86", target_arch = "x86_64"))'.dependencies]
jemallocator = "0.5"