[package]
name = "bus_benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
lqos_bus = { path = "../lqos_bus" }
tokio = { version = "1.22", features = [ "rt", "macros", "net", "io-util" ] }
anyhow = "1"
