[package]
name = "lqos_python"
version = "0.1.0"
edition = "2021"

[lib]
name = "lqos_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.17"
lqos_bus = { path = "../lqos_bus" }
tokio = { version = "1", features = [ "rt", "macros", "net", "io-util", "time" ] }
anyhow = "1"
sysinfo = "0"
nix = "0"
