name: Rust

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update; sudo apt-get install --no-install-recommends python3-pip clang gcc gcc-multilib llvm libelf-dev git nano graphviz curl screen llvm pkg-config linux-tools-common linux-tools-`uname r` libbpf-dev
      if: matrix.os == 'ubuntu-latest'
    - name: Build
      run: pushd src/rust; cargo build --verbose --all; popd
    - name: Run tests
      run: pushd src/rust; cargo test --verbose --all; popd
  
  audit:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install tools
      run: pushd src/rust; cargo install cargo-outdated; popd
    - name: Check for outdated dependencies
      run: cd src/rust; cargo outdated -w --color=always --root-deps-only --exit-code 1
    - name: rust-audit-check
      uses: actions-rs/audit-check@v1.2.0

